backend:
  # Use the Git Gateway backend for authentication via Netlify Identity.  The
  # branch setting determines which branch content updates will be committed to.
  name: git-gateway
  branch: main

local_backend: true

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  # Define a single collection for blog posts.  Each markdown file lives in
  # the `posts` directory at the project root.  You can add more collections
  # here (e.g. for projects or pages) as your site grows.
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime" }
      - { name: "categories", label: "Categories", widget: "list", required: false }
      - { name: "excerpt", label: "Excerpt", widget: "text" }
      - { name: "image", label: "Featured Image", widget: "image", required: false }
      - { name: "body", label: "Body", widget: "markdown" }
